[phases.setup]
nixPkgs = ["python311", "postgresql_16.dev", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete - migrations will run on startup'"]

[phases.release]
cmds = ["echo 'Skipping release phase'"]

[start]
cmd = "sh -c 'python manage.py migrate && python manage.py collectstatic --noinput && gunicorn alphalpgas.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level debug'"
