# Generated by Django 4.2.7 on 2026-05-01 09:14

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    """
    Align BlogPage model with the actual database state.
    On Railway, the table is already cms_blogpost with featured_image_id.
    Locally, the table may be cms_blogpage without featured_image_id.
    """
    connection = schema_editor.connection
    cursor = connection.cursor()

    # Check if cms_blogpost already exists (Railway state)
    cursor.execute(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'cms_blogpost')"
    )
    blogpost_exists = cursor.fetchone()[0]

    # Check if cms_blogpage exists (local/fresh state from 0001_initial)
    cursor.execute(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'cms_blogpage')"
    )
    blogpage_exists = cursor.fetchone()[0]

    if blogpost_exists:
        # Railway state: table already correct, just ensure featured_image_id column exists
        cursor.execute(
            "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
            "WHERE table_name = 'cms_blogpost' AND column_name = 'featured_image_id')"
        )
        has_featured_image = cursor.fetchone()[0]
        if not has_featured_image:
            cursor.execute(
                'ALTER TABLE cms_blogpost ADD COLUMN featured_image_id integer NULL '
                'REFERENCES wagtailimages_image(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED'
            )
            cursor.execute(
                'CREATE INDEX IF NOT EXISTS cms_blogpost_featured_image_id_idx ON cms_blogpost (featured_image_id)'
            )
    elif blogpage_exists:
        # Local state: rename table and add column
        cursor.execute('ALTER TABLE cms_blogpage RENAME TO cms_blogpost')
        cursor.execute(
            'ALTER TABLE cms_blogpost ADD COLUMN featured_image_id integer NULL '
            'REFERENCES wagtailimages_image(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED'
        )
        cursor.execute(
            'CREATE INDEX IF NOT EXISTS cms_blogpost_featured_image_id_idx ON cms_blogpost (featured_image_id)'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='blogpage',
                    name='featured_image',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
                ),
                migrations.AlterModelTable(
                    name='blogpage',
                    table='cms_blogpost',
                ),
            ],
            database_operations=[],
        ),
    ]
