# Generated by Django 4.2.7 on 2025-10-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Door to Door LPG Gas Delivery', max_length=255)),
                ('subtitle', models.TextField(default='Fast, reliable gas delivery to your doorstep in Fish Hoek and surrounding areas. Order online and get same-day delivery!')),
                ('background_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='banners/')),
                ('cta_text', models.CharField(default='Order Now', help_text='Call-to-action button text', max_length=100)),
                ('cta_link', models.CharField(default='#order', help_text='Call-to-action button link', max_length=255)),
                ('secondary_cta_text', models.CharField(blank=True, default='View Products', help_text='Secondary button text', max_length=100)),
                ('secondary_cta_link', models.CharField(blank=True, default='#products', help_text='Secondary button link', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Display this banner on the website')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
