# Generated by Django 4.2.7 on 2025-10-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_herobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='overlay_color',
            field=models.CharField(choices=[('blue', 'Blue (Default)'), ('rose', 'Rose/Red'), ('green', 'Green'), ('purple', 'Purple'), ('gray', 'Gray'), ('black', 'Black'), ('none', 'No Overlay')], default='blue', help_text='Background overlay color (only applies if background image is set)', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='overlay_opacity',
            field=models.IntegerField(default=85, help_text='Overlay opacity percentage (0-100). Higher = more opaque'),
        ),
    ]
