# Generated by Django 4.2.7 on 2025-10-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text="Customer's name", max_length=255)),
                ('location', models.CharField(help_text="e.g., Fish Hoek, Kommetjie, Simon's Town", max_length=255)),
                ('review', models.TextField(help_text="Customer's testimonial")),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Star rating (1-5)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on the website')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('company_name', models.CharField(blank=True, help_text='Company name (for business customers)', max_length=255)),
                ('avatar_color', models.CharField(choices=[('blue', 'Blue'), ('rose', 'Rose'), ('green', 'Green'), ('purple', 'Purple'), ('yellow', 'Yellow'), ('red', 'Red')], default='blue', help_text='Avatar background color', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
