# Generated by Django 4.2.7 on 2025-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_invoice_message',
            field=models.TextField(blank=True, help_text='Pre-populated WhatsApp message for sending invoice to client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_sent',
            field=models.BooleanField(default=False, help_text='Whether invoice has been sent via WhatsApp'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, help_text='When invoice was sent via WhatsApp', null=True),
        ),
    ]
