# Generated by Django 4.2.7 on 2025-11-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_whatsapp_fields_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon (recommended: 32x32px or 64x64px PNG/ICO)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (recommended: 200x200px PNG with transparent background)', null=True, upload_to='branding/'),
        ),
    ]
