# Generated by Django 4.2.7 on 2025-11-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_add_logo_favicon_to_company_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('id_number', models.CharField(blank=True, help_text='ID or passport number', max_length=50)),
                ('address', models.TextField(blank=True)),
                ('vehicle_type', models.CharField(help_text='e.g., Bakkie, Van, Truck', max_length=100)),
                ('vehicle_registration', models.CharField(help_text='Vehicle registration number', max_length=50)),
                ('vehicle_make_model', models.CharField(blank=True, help_text='e.g., Toyota Hilux', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_delivery', 'On Delivery'), ('off_duty', 'Off Duty'), ('on_break', 'On Break')], default='available', max_length=20)),
                ('drivers_license_number', models.CharField(blank=True, max_length=50)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Average rating out of 5', max_digits=3)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the driver')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Driver assigned to this delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='core.driver'),
        ),
    ]
