# Generated by Django 4.2.7 on 2025-12-29 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_driver_order_assigned_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name (e.g., Google Tag Manager, Facebook Pixel)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this script does')),
                ('script_code', models.TextField(help_text='The script code to inject (including <script> tags if needed)')),
                ('position', models.CharField(choices=[('head_start', 'Head Start (Beginning of <head>)'), ('head_end', 'Head End (End of <head>)'), ('body_start', 'Body Start (Beginning of <body>)'), ('body_end', 'Body End (End of <body>)'), ('footer', 'Footer (Before closing </body>)')], default='head_end', help_text='Where to inject this script', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this script')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('apply_to_all_pages', models.BooleanField(default=True, help_text='Apply to all pages')),
                ('specific_pages', models.TextField(blank=True, help_text='Comma-separated URL patterns (e.g., /products/, /checkout/). Leave blank if applying to all pages.')),
                ('exclude_pages', models.TextField(blank=True, help_text='Comma-separated URL patterns to exclude (e.g., /admin/, /driver/)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_scripts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Script',
                'verbose_name_plural': 'Custom Scripts',
                'ordering': ['order', 'name'],
            },
        ),
    ]
