# Generated by Django 4.2.7 on 2025-12-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_customscript'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customscript',
            options={'ordering': ['placement', 'order', 'name'], 'verbose_name': 'Custom Script', 'verbose_name_plural': 'Custom Scripts'},
        ),
        migrations.RemoveField(
            model_name='customscript',
            name='apply_to_all_pages',
        ),
        migrations.RemoveField(
            model_name='customscript',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customscript',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customscript',
            name='exclude_pages',
        ),
        migrations.RemoveField(
            model_name='customscript',
            name='position',
        ),
        migrations.RemoveField(
            model_name='customscript',
            name='specific_pages',
        ),
        migrations.AddField(
            model_name='customscript',
            name='apply_to_backend',
            field=models.BooleanField(default=True, help_text='Apply to Django backend templates (accounting, driver portal)'),
        ),
        migrations.AddField(
            model_name='customscript',
            name='apply_to_frontend',
            field=models.BooleanField(default=True, help_text='Apply to Next.js frontend (via API)'),
        ),
        migrations.AddField(
            model_name='customscript',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this script'),
        ),
        migrations.AddField(
            model_name='customscript',
            name='placement',
            field=models.CharField(choices=[('head', 'Head (inside <head> tag)'), ('body_start', 'Body Start (after opening <body> tag)'), ('body_end', 'Body End / Footer (before closing </body> tag)')], default='head', help_text='Where to inject the script', max_length=20),
        ),
        migrations.AlterField(
            model_name='customscript',
            name='name',
            field=models.CharField(help_text="Descriptive name for the script (e.g., 'Google Tag Manager')", max_length=255),
        ),
        migrations.AlterField(
            model_name='customscript',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of execution (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='customscript',
            name='script_code',
            field=models.TextField(help_text='The full script code including <script> tags or noscript tags'),
        ),
    ]
