# Generated by Django 4.2.7 on 2026-01-02 14:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_add_accounting_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 5kg, 9kg, 14kg, 19kg, 48kg', max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cylinder Size',
                'verbose_name_plural': 'Cylinder Sizes',
                'ordering': ['weight_kg'],
            },
        ),
        migrations.CreateModel(
            name='StockPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('total_cylinders', models.IntegerField(default=0)),
                ('total_volume_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice_number', models.CharField(blank=True, help_text='Supplier invoice number', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_purchases_created', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_purchases', to='core.expense')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_purchases', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Stock Purchase',
                'verbose_name_plural': 'Stock Purchases',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cylinder_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cylindersize')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.stockpurchase')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase (Stock In)'), ('sale', 'Sale/Exchange (Stock Out)'), ('adjustment', 'Manual Adjustment'), ('transfer', 'Transfer'), ('return', 'Customer Return'), ('damage', 'Damaged/Write-off')], max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('reference', models.CharField(blank=True, help_text='Invoice/PO number, etc.', max_length=100)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per cylinder', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('cylinder_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.cylindersize')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.expense')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.invoice')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.invoiceitem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GasStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Number of full cylinders in stock')),
                ('reorder_level', models.IntegerField(default=10, help_text='Minimum stock before reorder alert')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cylinder_size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='core.cylindersize')),
            ],
            options={
                'verbose_name': 'Gas Stock',
                'verbose_name_plural': 'Gas Stock Levels',
            },
        ),
    ]
