# Generated by Django 4.2.7 on 2026-01-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_stock_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Whether stock has been deducted for this item'),
        ),
    ]
