# Generated by Django 4.2.7 on 2026-01-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_stock_deducted_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, help_text='Delivery zone for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.deliveryzone'),
        ),
    ]
