# Generated by Django 4.2.7 on 2026-02-02 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_add_delivery_zone_to_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_size', models.CharField(choices=[('5kg', '5kg Cylinder'), ('9kg', '9kg Cylinder'), ('19kg', '19kg Cylinder'), ('48kg', '48kg Cylinder')], max_length=10)),
                ('stamps', models.IntegerField(default=0, help_text='Number of stamps (purchases) on this card')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to='core.client')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('client', 'cylinder_size', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stamp', 'Stamp Added'), ('reward_claimed', 'Reward Claimed'), ('card_reset', 'Card Reset')], max_length=20)),
                ('stamps_before', models.IntegerField()),
                ('stamps_after', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='core.invoice')),
                ('loyalty_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.loyaltycard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
