# Generated by Django 4.2.7 on 2026-02-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_loyaltycard_loyaltytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_note',
            field=models.TextField(blank=True, help_text='Delivery instructions or notes for the driver'),
        ),
    ]
