# Generated by Django 4.2.7 on 2026-02-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_invoice_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company or business name', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='company_reg',
            field=models.CharField(blank=True, help_text='Company registration number', max_length=100),
        ),
    ]
