# Generated by Django 4.2.7 on 2026-02-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_company_fields_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Default VAT/Tax rate (%) applied to invoices, quotes, and credit notes', max_digits=5),
        ),
    ]
