# Generated by Django 4.2.7 on 2026-02-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_default_tax_rate_to_company_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_loyalty_message',
            field=models.TextField(blank=True, default='Hi {client_name}, thank you for your loyalty to {company_name}! Your {cylinder_size} loyalty card now has {stamps}/9 stamps. {reward_text} Keep purchasing to earn your reward! Best regards, {company_name} Team', help_text='WhatsApp message template for loyalty cards. Available variables: {client_name}, {company_name}, {cylinder_size}, {stamps}, {remaining}, {reward_text}'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='whatsapp_loyalty_reward_message',
            field=models.TextField(blank=True, default='🎉 Congratulations {client_name}! You have earned {reward_type} on your next {cylinder_size} cylinder purchase from {company_name}! Present this message to claim your reward. Thank you for your loyalty! Best regards, {company_name} Team', help_text='WhatsApp message for when a loyalty card reaches 9 stamps. Available variables: {client_name}, {company_name}, {cylinder_size}, {reward_type}'),
        ),
    ]
