# Generated by Django 4.2.7 on 2026-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_whatsapp_loyalty_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount to be subtracted from total', max_digits=10),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='whatsapp_loyalty_reward_message',
            field=models.TextField(blank=True, default='🎉 Congratulations {client_name}! You have earned {reward_type} from {company_name}! Present this message to claim your reward. Thank you for your loyalty! Best regards, {company_name} Team', help_text='WhatsApp message for when a loyalty card reaches 9 stamps. Available variables: {client_name}, {company_name}, {cylinder_size}, {reward_type}'),
        ),
    ]
