# Generated by Django 4.2.7 on 2026-02-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_make_payment_invoice_nullable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'show_on_website'], name='core_produc_is_acti_a71fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='core_produc_is_feat_ba4bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='core_produc_categor_9c2292_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['order'], name='core_produc_order_ee4c25_idx'),
        ),
    ]
