# Generated by Django 4.2.7 on 2026-02-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_product_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'payment_method'], name='core_paymen_payment_d22b04_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'payment_date'], name='core_paymen_invoice_6c7f35_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-payment_date'], name='core_paymen_payment_acb694_idx'),
        ),
    ]
