# Generated by Django 4.2.7 on 2026-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_simplify_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycard',
            name='cylinder_size',
            field=models.CharField(choices=[('5kg', '5kg Cylinder'), ('9kg', '9kg Cylinder'), ('14kg', '14kg Cylinder'), ('19kg', '19kg Cylinder'), ('48kg', '48kg Cylinder')], max_length=10),
        ),
    ]
