# Generated by Django 4.2.7 on 2026-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_14kg_cylinder_to_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('stamp', 'Stamp Added'), ('reward_claimed', 'Reward Claimed'), ('card_reset', 'Card Reset'), ('reversal', 'Stamp Reversal')], max_length=20),
        ),
    ]
