# Generated by Django 4.2.7 on 2026-03-10 11:58

from django.db import migrations


def consolidate_loyalty_cards(apps, schema_editor):
    """Consolidate multiple loyalty cards per client into a single card"""
    LoyaltyCard = apps.get_model('core', 'LoyaltyCard')
    LoyaltyTransaction = apps.get_model('core', 'LoyaltyTransaction')
    
    # Find all clients with multiple active cards
    from django.db.models import Count
    clients_with_duplicates = LoyaltyCard.objects.filter(is_active=True).values('client_id').annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    size_order = ['5kg', '9kg', '14kg', '19kg', '48kg']
    
    for client_data in clients_with_duplicates:
        client_id = client_data['client_id']
        cards = LoyaltyCard.objects.filter(client_id=client_id, is_active=True).order_by('created_at')
        
        # Keep the first card, merge others into it
        primary_card = cards.first()
        other_cards = cards[1:]
        
        # Find smallest cylinder size across all cards
        smallest_size = primary_card.cylinder_size
        total_stamps = primary_card.stamps
        
        for card in other_cards:
            # Add stamps from this card
            total_stamps += card.stamps
            
            # Update smallest cylinder size
            if card.cylinder_size and smallest_size:
                if size_order.index(card.cylinder_size) < size_order.index(smallest_size):
                    smallest_size = card.cylinder_size
            elif card.cylinder_size:
                smallest_size = card.cylinder_size
            
            # Move all transactions to primary card
            LoyaltyTransaction.objects.filter(loyalty_card=card).update(loyalty_card=primary_card)
            
            # Delete the duplicate card
            card.delete()
        
        # Update primary card with consolidated data
        primary_card.stamps = total_stamps
        primary_card.cylinder_size = smallest_size
        primary_card.save()


def reverse_consolidation(apps, schema_editor):
    """Cannot reverse this migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_reversal_transaction_type'),
    ]

    operations = [
        migrations.RunPython(consolidate_loyalty_cards, reverse_consolidation),
    ]
