# Generated by Django 4.2.7 on 2026-03-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_consolidate_duplicate_loyalty_cards'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loyaltycard',
            unique_together={('client', 'is_active')},
        ),
        migrations.AlterField(
            model_name='loyaltycard',
            name='cylinder_size',
            field=models.CharField(blank=True, choices=[('5kg', '5kg Cylinder'), ('9kg', '9kg Cylinder'), ('14kg', '14kg Cylinder'), ('19kg', '19kg Cylinder'), ('48kg', '48kg Cylinder')], help_text='Smallest cylinder size purchased (determines reward type)', max_length=10, null=True),
        ),
    ]
