# Generated by Django 4.2.7 on 2026-03-29 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_taxconfiguration_vatreturn_sarstaxreturn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(help_text='WhatsApp Business Phone Number ID', max_length=255)),
                ('business_account_id', models.CharField(help_text='WhatsApp Business Account ID', max_length=255)),
                ('access_token', models.CharField(help_text='WhatsApp API Access Token', max_length=500)),
                ('webhook_verify_token', models.CharField(help_text='Webhook verification token', max_length=255)),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI (GPT-4)'), ('anthropic', 'Anthropic (Claude)')], default='openai', max_length=20)),
                ('ai_api_key', models.CharField(help_text='API key for AI provider', max_length=500)),
                ('ai_model', models.CharField(default='gpt-4o', help_text='AI model to use', max_length=100)),
                ('auto_create_invoices', models.BooleanField(default=True, help_text='Automatically create invoices for confirmed orders')),
                ('auto_assign_drivers', models.BooleanField(default=True, help_text='Automatically assign available drivers')),
                ('min_confidence_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='Minimum AI confidence to auto-process (0-100)', max_digits=5)),
                ('business_hours_start', models.TimeField(default='08:00', help_text='Start of business hours')),
                ('business_hours_end', models.TimeField(default='18:00', help_text='End of business hours')),
                ('auto_respond_outside_hours', models.BooleanField(default=True, help_text='Send automated response outside business hours')),
                ('outside_hours_message', models.TextField(default="Thank you for your message! Our business hours are 8 AM - 6 PM. We'll respond to your message as soon as we're back.", help_text='Message to send outside business hours')),
                ('welcome_message', models.TextField(default='Hi! Welcome to Alpha LPGas 🔥\n\nHow can I help you today?\n\n1️⃣ Order gas cylinders\n2️⃣ Check order status\n3️⃣ View products & prices\n4️⃣ Speak to a person\n\nJust type your request!', help_text='Welcome message for new conversations')),
                ('system_prompt', models.TextField(default="You are a helpful AI assistant for Alpha LPGas, a gas delivery company in South Africa.\n\nYour role is to:\n1. Help customers order gas cylinders (9kg, 14kg, 19kg, 48kg)\n2. Extract order details: product type, quantity, delivery address\n3. Confirm order details with the customer\n4. Be friendly, professional, and efficient\n\nWhen a customer wants to order:\n- Ask for: product type, quantity, and delivery address\n- Confirm all details before processing\n- Provide estimated delivery time\n\nIf you're unsure about anything, ask for clarification or escalate to a human agent.", help_text='System prompt for AI agent')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable WhatsApp integration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Configuration',
                'verbose_name_plural': 'WhatsApp Configuration',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Client's WhatsApp number", max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('escalated', 'Escalated to Human'), ('archived', 'Archived')], default='active', max_length=20)),
                ('conversation_context', models.JSONField(default=dict, help_text='Stores conversation state and extracted information')),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('ai_confidence_score', models.DecimalField(decimal_places=2, default=0, help_text='AI confidence in understanding (0-100)', max_digits=5)),
                ('requires_human', models.BooleanField(default=False, help_text='Flag for human intervention needed')),
                ('escalation_reason', models.TextField(blank=True, help_text='Reason for escalation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member handling escalation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='core.client')),
                ('created_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='core.invoice')),
                ('created_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='core.order')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (from client)'), ('outbound', 'Outbound (to client)')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('location', 'Location')], default='text', max_length=20)),
                ('content', models.TextField(help_text='Message text content')),
                ('media_url', models.URLField(blank=True, help_text='URL to media file if applicable')),
                ('whatsapp_message_id', models.CharField(help_text='WhatsApp message ID', max_length=255, unique=True)),
                ('whatsapp_timestamp', models.DateTimeField(help_text='Timestamp from WhatsApp')),
                ('ai_processed', models.BooleanField(default=False, help_text='Whether AI has processed this message')),
                ('ai_intent', models.CharField(blank=True, help_text="Detected intent (e.g., 'place_order', 'check_status')", max_length=100)),
                ('ai_extracted_data', models.JSONField(default=dict, help_text='Data extracted by AI (products, quantities, etc.)')),
                ('ai_response', models.TextField(blank=True, help_text='AI-generated response')),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.whatsappconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOrderIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed by Client'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('products_data', models.JSONField(help_text='List of products with quantities and prices')),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence in order details (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_intents', to='core.whatsappconversation')),
                ('created_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invoice')),
                ('created_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.order')),
                ('delivery_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deliveryzone')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_intents', to='core.whatsappmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='core_whatsa_convers_64b904_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['whatsapp_message_id'], name='core_whatsa_whatsap_d59914_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['ai_processed', 'direction'], name='core_whatsa_ai_proc_aac8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['phone_number', '-last_message_at'], name='core_whatsa_phone_n_859fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['status', '-last_message_at'], name='core_whatsa_status_4d2514_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['requires_human', '-last_message_at'], name='core_whatsa_require_50caf5_idx'),
        ),
    ]
