# Generated by Django 4.2.7 on 2026-05-01 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_alter_product_cost_price_alter_product_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_see_sales', models.BooleanField(default=True, verbose_name='Sales menu')),
                ('can_see_people', models.BooleanField(default=True, verbose_name='People menu')),
                ('can_see_products', models.BooleanField(default=True, verbose_name='Products menu')),
                ('can_see_orders', models.BooleanField(default=True, verbose_name='Orders menu')),
                ('can_see_accounting', models.BooleanField(default=True, verbose_name='Accounting menu')),
                ('can_see_admin', models.BooleanField(default=True, verbose_name='Admin link')),
                ('can_see_quotes', models.BooleanField(default=True, verbose_name='Quotes')),
                ('can_see_invoices', models.BooleanField(default=True, verbose_name='Invoices')),
                ('can_see_payments', models.BooleanField(default=True, verbose_name='Payments')),
                ('can_see_eft_reconciliation', models.BooleanField(default=True, verbose_name='EFT Reconciliation')),
                ('can_see_credit_notes', models.BooleanField(default=True, verbose_name='Credit Notes')),
                ('can_see_loyalty_cards', models.BooleanField(default=True, verbose_name='Loyalty Cards')),
                ('can_see_sales_report', models.BooleanField(default=True, verbose_name='Sales Report')),
                ('can_see_clients', models.BooleanField(default=True, verbose_name='Clients')),
                ('can_see_suppliers', models.BooleanField(default=True, verbose_name='Suppliers')),
                ('can_see_drivers', models.BooleanField(default=True, verbose_name='Drivers')),
                ('can_see_contact_submissions', models.BooleanField(default=True, verbose_name='Contact Submissions')),
                ('can_see_all_orders', models.BooleanField(default=True, verbose_name='All Orders')),
                ('can_see_delivery_zones', models.BooleanField(default=True, verbose_name='Delivery Zones')),
                ('can_see_chart_of_accounts', models.BooleanField(default=True, verbose_name='Chart of Accounts')),
                ('can_see_journal_entries', models.BooleanField(default=True, verbose_name='Journal Entries')),
                ('can_see_vat_returns', models.BooleanField(default=True, verbose_name='VAT Returns')),
                ('can_see_sars_tax_returns', models.BooleanField(default=True, verbose_name='SARS Tax Returns')),
                ('can_see_cipc_annual_returns', models.BooleanField(default=True, verbose_name='CIPC Annual Returns')),
                ('can_see_financial_statements', models.BooleanField(default=True, verbose_name='Financial Statements')),
                ('can_see_tax_configuration', models.BooleanField(default=True, verbose_name='Tax Configuration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Menu Permission',
                'verbose_name_plural': 'User Menu Permissions',
            },
        ),
    ]
