# Generated by Django 4.2.7 on 2026-06-19 07:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0038_user_menu_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierGasRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, help_text='Rate per kilogram in Rands', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('effective_month', models.DateField(help_text='First day of the month this rate applies to')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_rates_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_rates', to='core.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Gas Rate',
                'verbose_name_plural': 'Supplier Gas Rates',
                'ordering': ['-effective_month', 'supplier__name'],
                'unique_together': {('supplier', 'effective_month')},
            },
        ),
    ]
