# Generated by Django 4.2.7 on 2026-10-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_add_invoice_date_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Delivery order generated from this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='core.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Linked client account (matched or created on invoicing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.client'),
        ),
    ]
