# Generated by Django 4.2.7 on 2026-10-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_invoice_order_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invoice_item',
            field=models.ForeignKey(blank=True, help_text='Invoice line item this order item was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.invoiceitem'),
        ),
    ]
